-- AlterTable ScheduledReport
ALTER TABLE "ScheduledReport" ADD COLUMN IF NOT EXISTS "nextRunAt" TIMESTAMP(3);
ALTER TABLE "ScheduledReport" ADD COLUMN IF NOT EXISTS "reportType" TEXT NOT NULL DEFAULT 'EXECUTIVE_SUMMARY';
ALTER TABLE "ScheduledReport" ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'UTC';

-- AlterTable ReportDeliveryLog
ALTER TABLE "ReportDeliveryLog" ADD COLUMN IF NOT EXISTS "providerMessageId" TEXT;
ALTER TABLE "ReportDeliveryLog" ADD COLUMN IF NOT EXISTS "reportPeriod" TEXT;
ALTER TABLE "ReportDeliveryLog" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
